### ISSUE TITLE
referencia a otros objetos

### ISSUE THREAD

**Issue by adrianmeca** [Biscaldi-Iv/Construcciones#2]
https://github.com/Biscaldi-Iv/Construcciones/blob/0268ac891eb37c149caced04d2326b3c3321d8ca/src/main/java/entidades/Material.java#L38

no deberías usar ids de otros objetos para referenciar si no objetos enteros embebidos

**Comment by Biscaldi-Iv** [comment]
Lo hice pero al reves. Puse una lista de materiales para cada proveedor, y los materiales se recuperan a traves del objeto provedor
